server:
  port: 8080
  max-http-header-size: 10000000
  tomcat:
    basedir: /tmp/tomcat
  custom:
    httpPort: 8890
  servlet:
    session:
      timeout: 1800
  ssl:
    key-store: classpath:server.keystore
    key-store-password: changeit
    key-store-type: JKS
    key-alias: tomcat
spring:
  redis:
    database: 3           # Redis服务器数据库
    host: ${redis.host:127.0.0.1}   # Redis服务器地址
    port: ${redis.port:6379}         # Redis服务器连接端口
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  thymeleaf:
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


